# application.properties
#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:testdb

# application.yml
spring:
  h2:
    console:
      enabled: true

  datasource:
    url: "jdbc:h2:mem:testdb"
